### ISSUE TITLE
Enable circleci testing?

### ISSUE THREAD

**Issue by ryantxu** [panodata/grafana-map-panel#6]
while working on getting this ready to merge, it would be great to have circle doing the integration and distribution.

Can someone from the hiveeyes project enable it in circleci?

I think just login to circle and allow it to look at github:
https://circleci.com/add-projects/gh/hiveeyes

**Comment by amotl** [comment]
Dear Ryan,

thanks for your guideline. We will get an account there and add appropriate permissions.

With kind regards,
Andreas.

**Comment by amotl** [comment]
We just pressed some buttons and now something is here [1]. Have we been successful in this?

[1] https://circleci.com/gh/hiveeyes/workflows/grafana-worldmap-panel

**Comment by ryantxu** [comment]
perfect -- thank you!

**Comment by amotl** [comment]
Dear @ryantxu,

we've just moved the repository to the "panodata" organization. We haven't found a way to make CircleCI follow the move yet, so I will reopen this issue until one of us can confirm the CI pipeline still works.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @ryantxu,

we believe we successfully enabled the new repository location within CircleCI. The new location there is now https://circleci.com/gh/panodata/grafana-worldmap-panel.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear @ryantxu,

we just added CircleCI-testing against Grafana 6.4.4 and updated `yarn.lock`, which slipped through. While all tests are successful Now, the "report" job is failing again. Might the renaming (#21) be the reason for that?

May I humbly ask you to have a look / quickly fix things again in order to heal that CircleCI pipeline?

Thanks already and with kind regards,
Andreas.

[1] https://circleci.com/gh/panodata/grafana-map-panel/122
