### ISSUE TITLE
Problems matching JSON endpoint with Flux query data

### ISSUE THREAD

**Issue by MadWalnut** [panodata/grafana-map-panel#91]
Hi,

first of all thanks for this great fork. 

I've been trying to setup some basic data to show on the map at a location defined in a custom JSON. I followed [this format](https://github.com/panodata/grafana-map-panel#time-series-format) and adapted it slightly to my data.

I just want to show one data point on the map for the moment. This is the Flux query (InfluxDB v2):
```
from(bucket: "test")
|> range(start: -1h)
|> filter(fn: (r) =>
    r._field == "Crest_electrical_pump"
)
|> last()
```
This returns: 
![Screenshot_8](https://user-images.githubusercontent.com/33835479/107567090-c57e3e80-6be5-11eb-9591-527ba3bf2583.png)
Or how Grafana sees it:
![Screenshot_7](https://user-images.githubusercontent.com/33835479/107567184-d038d380-6be5-11eb-8a85-064327533a91.png)

So now I want to get this value to display on the map panel, by providing the coordinates via my JSON endpoint:
```
[
  {
    "key": "Crest_electrical_pump",
    "latitude": 43.790557,
    "longitude": 1.414478,
    "name": "Toulouse"
  }
]
```

These are my panel settings:
![Screenshot_6](https://user-images.githubusercontent.com/33835479/107567941-a16f2d00-6be6-11eb-80d0-23fff2d6049c.png)

I don't get any errors, there are just no circles appearing on the map. I feel like I am missing something really basic... I guess something is off with the JSON key but I don't know what else my key should be? 

Hope it was ok to open an issue for this, did not know where else to post.

Thanks in advance.

**Comment by amotl** [comment]
Hi @MadWalnut,

> first of all thanks for this great fork. Hope it was ok to open an issue for this, did not know where else to post.

thanks for the kind words. It is the perfect place to report your observations, thank you.

First of all, it is great to see that querying data using Flux apparently seems to be supported these days without further ado. @wetterfrosch will like that very much, see #22.

Regarding the problem you are observing, we will have to look into it in more detail. However, let me share some thoughts first. If you believe you did everything right on the first hand, the success might be missing because the outcome of the Flux query might not resonate well with the map machinery picking it up properly.

This, one the one hand, could be related to incorrect aliasing of the key field used for correlating data coming back from InfluxDB with the data within the JSON resource. On the other hand, the reason might be that the highlevel format coming back does not resonate well with the machinery at all, because it might happen that we see architecture changes now hitting the fan related to the new _Grafana DataFrame type_ being introduced into the framework.

As you can see from the settings dialog, Grafana historically had the notion of _table format_ vs. _timeseries format_ and the people at Grafana Labs have been working towards unifying that into the new DataFrame format [1] used as a primary data model to shuffle information around. While that has been introduced with Grafana 6.4.0 already, it might be the case that some compatibility shim made Grafana Map Panel still work. This may have changed with recent releases.

So, in order to get hold of the problem, may I humbly ask a) which version of Grafana you are using and b) whether you see any traces of errors happening when looking at the output on the JavaScript console of your browser?

With kind regards,
Andreas.

[1] https://community.panodata.org/t/the-grafana-dataframe-type/73

**Comment by MadWalnut** [comment]
And there we have that simple thing that totally went over my head. I'm new to Grafana and did not know you could check the error output in the JavaScript console. Thanks for the hint! 

This is the error I was getting: 
![Screenshot_9](https://user-images.githubusercontent.com/33835479/107651453-d11e4380-6c7f-11eb-8e0b-5e8e1473339b.png)

After that it was a simple fix, I allowed my Grafana host in the CORS policy of the webserver serving the JSON file.

Now everything works like a charm on Grafana 7.4.

Thanks again for your detailed response!

**Comment by amotl** [comment]
Hi @MadWalnut,

great to hear it works for you. At the same time, it was great to hear that Flux queries are finally possible to use with the Map Panel without further ado. As mentioned above, @wetterfrosch will like this. So, I believe we can also close #22.

Finally, I want to humbly ask if it would be possible to tell us more about your specific use case. This would give us some material to eventually establish a nice gallery within the documentation. @DmitrySidorow and @jm66 already chimed in on behalf of #90. Thanks!

With kind regards,
Andreas.

**Comment by MadWalnut** [comment]
I'm afraid I cannot give you screenshots of my scenario just yet as this setup is merely a proof of concept for now and I do not have access to real data right now. I have just picked up Grafana and am still learning / integrating everything.

Basically the idea is to create a dashboard for internal use with which we can monitor the performace / health of several IoT devices all around the world. This data is currently fed into InfluxDB (which again may not be a final solution as I am testing different tools as part of the POC). The main two reasons I quickly switched to this worldmap fork is the ability to get locations from a different source (sending them together with the IoT data is not practical as we have changing locations) and the ability to click on the bubbles and dive further into more in-depth metrics from that specific device. 

If we decide to stick with Grafana as a whole, I'll be happy to share screenshots of the final setup. I hope the explanation of our use case is fine for now and you can get something out of it.

Thank you!

**Comment by amotl** [comment]
Hi @MadWalnut,

all right. Thanks for letting us know about your rough direction. We are actually doing similar things with Kotori [1], data is converged into public Grafana instances available at [2] and [3], which you also might want to enjoy.

Good luck with your project!

With kind regards,
Andreas.

[1] https://getkotori.org/
[2] https://swarm.hiveeyes.org/
[3] https://weather.hiveeyes.org/
